services:
  ripper-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "127.0.0.1:8080:${API_PORT}"
    volumes:
      - "/var/www/amusic:${WEB_DIR}"
    environment:
      PORT: ${API_PORT}
      WEB_DIR: ${WEB_DIR}
      WRAPPERS: "wrapper:${WRAPPER_PORT},127.0.0.1:10021"
      KEY_DB: ${KEY_DB}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_ADDRESS: "${REDIS_ADDRESS}:${REDIS_PORT}"
    container_name: ripper-api
    depends_on:
      redis:
        condition: service_started
      wrapper:
        condition: service_started

  redis:
    image: redis:latest
    restart: always
    ports:
      - "127.0.0.1:6379:${REDIS_PORT}"
    container_name: redis-db
  
  wrapper:
    build:
      dockerfile: Dockerfile-wrapper
    privileged: true
    restart: always
    ports:
      - "127.0.0.1:10200:${WRAPPER_PORT}"
    environment:
      WRAPPER_HOST: "0.0.0.0"
      WRAPPER_PORT: "${WRAPPER_PORT}"
      AMUSIC_ACCOUNT: "${AMUSIC_ACCOUNT}"
    container_name: wrapper
