services:
  ripper-api:
    build: .
    ports:
      - "127.0.0.1:8080:80"
    environment:
      PORT: ${API_PORT}
      WEB_DIR: ${WEB_DIR}
      WRAPPER_PORT: ${WRAPPER_PORT}
      KEY_DB: ${KEY_DB}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    container_name: ripper-api

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis-db